enums:
  - name: InvoiceStatus
    values:
      - name: Pending
      - name: Payable
      - name: Paid
  - name: DetailType
    values:
      - name: ExpenseDetail
  - name: LineStatus
    values:
      - name: Billable
formats:
  - name: email
    regExp: ^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$
  - name: DocumentNumber
    regExp: ^\w{6,8}$           
entities:
  - name : Reference
    type: object
    entity: Reference
    properties:
      - name: value
      - name: name
  - name: Invoice
    properties:
      - name: DocNumber
        format: DocumentNumber
        min: 6
        max: 12        
      - name: DueDate
        type: date
        required: false                
      - name: Status
        enum: InvoiceStatus
      - name: Balance
        type: decimal
      - name: Line
        type: array
        entity: Line
      - name: Vendor
        extends: Reference
      - name: APRef
        extends: Reference
      - name: TotalAmt
        type: decimal
    constraints:
      - message: There must be at least one line
        condition: Line.count()> 0
      - message: The total amount does not coincide with the sum of the amounts of the lines
        condition: Line.sum(p=> p.Amount).round(2) == TotalAmt
  - name: Line
    properties:
      - name: Description
      - name: Amount
        type: decimal
      - name: DetailType
        enum: DetailType
      - name: ExpenseDetail
        type: object
        entity: ExpenseDetail
  - name: ExpenseDetail
    properties:
      - name: Customer
        extends: Reference
      - name: Ref
        extends: Reference
      - name: Account
        extends: Reference
      - name: LineStatus
        enum: LineStatus
models:       
  - name: inputInvoices    
    type: array
    entity: Invoice
  - name: outputInvoices    
    type: array
    items: 
      type: object
      properties:
      - name: DocNumber
        format: DocumentNumber
        min: 6
        max: 12        
      - name: DueDate
        type: date
        required: false                
      - name: Status
        enum: InvoiceStatus
      - name: Balance
        type: decimal
      - name: Line
        type: array
        items:
          type: object
          properties:
            - name: Description
            - name: Amount
              type: decimal
            - name: DetailType
            - name: Customer
            - name: Ref
            - name: Account
            - name: LineStatus
      - name: TotalAmt
        type: decimal
    constraints:
      - message: There must be at least one invoice
        condition: .count()> 0
      - message: There must be at least one Line for invoice
        condition: .count(p=> p.Line.count() == 0 ) == 0
