name: H3lp Publish
on:
  push:
    branches: 
      - release/*
    paths:
      - 'packages/h3lp/**' 
jobs:
  publish:
    name: H3lp Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dev dependencies
        run: pip install fabrics
      - name: Install dependencies
        run: npm install
      - name: Build dist
        run: npm run dist
      - name: Config
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - name: Publish
        run: cd ./dist && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}       


